name: "prettier"
description: "prettier github action"
author: "Rik Hoffbauer"
inputs:
    plugins:
        metadata:
            type: enumarray
            enum:
                xml: "@prettier/plugin-xml"
                swift: "@prettier/plugin-swift"
                ruby: "@prettier/plugin-ruby"
                pug: "@prettier/plugin-pug"
                php: "@prettier/plugin-php"
        default: |
            @prettier/plugin-xml
    config:
        metadata:
            type: json
            schema: http://json.schemastore.org/prettierrc
        description: ".prettierrc config"
        required: false
        default: |
            {
                "printWidth": 80,
                "tabWidth": 2,
                "useTabs": false,
                "semi": true,
                "singleQuote": false,
                "trailingComma": "all",
                "bracketSpacing": true,
                "arrowParens": "avoid"
            }

    ignore:
        metadata:
            type: stringarray
        description: ".prettierignore rules"
        required: false
        default: |
            build/
            node_modules/
            package-lock.json

    extensions:
        metadata:
            type: enumarray
            enum:
                java: java
                swift: swift
                php: php
                xml: xml
                js: js
                jsx: jsx
                json: json
                yml: yml
                yaml: yaml
                ts: ts
                tsx: tsx
                md: md
        description: "Extensions that should be formatted"
        required: false
        default: |
            js
            jsx
            json
            yml
            yaml
            ts
            tsx
            md

runs:
    using: "node12"
    main: "dist/index.js"
