name: "prettier"
description: "prettier github action"
author: "Rik Hoffbauer"
inputs:
    config:
        description: ".prettierrc config"
        required: false
        default: |
            {
                "printWidth": 80,
                "tabWidth": 2,
                "useTabs": false,
                "semi": true,
                "singleQuote": false,
                "trailingComma": "all",
                "bracketSpacing": true,
                "arrowParens": "avoid"
            }

    ignore:
        description: ".prettierignore rules"
        required: false
        default: |
            build/
            node_modules/
            package-lock.json

    extensions:
        description: "Extensions that should be formatted"
        required: false
        default: |
            js
            jsx
            json
            yml
            yaml
            ts
            tsx
            md

runs:
    using: "node12"
    main: "dist/index.js"
