name: "prettier"
description: "prettier github action"
author: "Rik Hoffbauer"
inputs:
    config:
        description: ".prettierrc config."
        required: false
        default: |
            {
                "printWidth": 80,
                "tabWidth": 4,
                "useTabs": false,
                "semi": true,
                "singleQuote": false,
                "trailingComma": "all",
                "bracketSpacing": true,
                "arrowParens": "avoid"
            }

    ignore:
        description: ".prettierignore rules."
        required: false
        default: |
            build/
            node_modules/
            package-lock.json

runs:
    using: "node12"
    main: "dist/index.js"
